name: flutter_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter   

  flutter_icons:
    git: https://github.com/jibiel/flutter-icons

  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  intl: ^0.19.0    
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  carousel_slider_plus: ^7.1.0
  retrofit: ^4.4.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  realm: ^20.0.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  badges: ^3.1.2
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true
  assets:
  - assets/images/no_image.jpg  

flutter_intl:
  enabled: true
